   name: Acesso Remoto
on: workflow_dispatch

jobs:
  conectar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Acesso Remoto
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Abrir Conexão
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Conexão estabelecida!"
          echo "Acesse usando o link SSH ou Web abaixo:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          
          # Mantém o PC ligado por 6 horas (limite do GitHub)
          sleep 21600
